# Generated by Django 4.0.5 on 2024-04-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Aditya', max_length=30)),
                ('age', models.IntegerField(default=1)),
            ],
        ),
    ]
